workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

railway-deploy-web:
  stage: deploy
  image: ghcr.io/railwayapp/cli:latest
  variables:
    SVC_ID: 71174d3a-51b3-4a02-9b52-bd85c816eeeb
  script:
    - railway up --service=$SVC_ID

railway-deploy-caddy:
  stage: deploy
  image: ghcr.io/railwayapp/cli:latest
  variables:
    SVC_ID: e80adf00-442d-413c-8528-20cb04f7fcf0
  script:
    - railway up --service=$SVC_ID
  rules:
    - changes:
        - caddy/*
