workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

railway-deploy-web:
  stage: deploy
  image: ghcr.io/railwayapp/cli:latest
  variables:
    SVC_ID: 0c17b7d5-5d73-4f11-a7be-edc64c0cf5d4
  script:
    - railway up --service=$SVC_ID

railway-deploy-caddy:
  stage: deploy
  image: ghcr.io/railwayapp/cli:latest
  variables:
    SVC_ID: 52e50462-9ba0-4d6e-803e-32b877bf5451
  script:
    - railway up --service=$SVC_ID
  rules:
    - changes:
        - caddy/*
        - finapp/static/**/*
