services:
  caddy:
    container_name: budget_caddy
    image: ghcr.io/niklasbaumgardner/budget-caddy:latest
    build:
      context: .
      dockerfile: caddy/Dockerfile
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    ports:
      - "8443:443"
    depends_on:
      - web
    networks:
      - budget-network
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped

  web:
    container_name: budget_web
    image: ghcr.io/niklasbaumgardner/budget:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 9090
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_USER: ${EMAIL_USER}
      SECRET_KEY: ${SECRET_KEY}
      SENTRY_DSN: ${SENTRY_DSN}
      SCOUT_KEY: ${SCOUT_KEY}
      SIMPLEFIN_KEY: ${SIMPLEFIN_KEY}
      FERNET_KEY: ${FERNET_KEY}
      SESSION_COOKIE_NAME: ${SESSION_COOKIE_NAME}
      REMEMBER_COOKIE_NAME: ${REMEMBER_COOKIE_NAME}
      SQLALCHEMY_DATABASE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@budget_pgbouncer:6432/${POSTGRES_DB}
    depends_on:
      - pgbouncer
    networks:
      - budget-network
    restart: unless-stopped

  pgbouncer:
    container_name: budget_pgbouncer
    image: railwayapp/pgbouncer
    ports:
      - "7432:6432"
    environment:
      POSTGRESQL_HOST: postgres
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
      PGBOUNCER_POOL_MODE: transaction
      PGBOUNCER_MIN_POOL_SIZE: 3
      PGBOUNCER_DATABASE: ${POSTGRES_DB}
      PGBOUNCER_LISTEN_ADDRESS: 0.0.0.0
    depends_on:
      - postgres
    networks:
      - budget-network
    restart: unless-stopped

  postgres:
    container_name: budget_postgres
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - budget-network
    restart: unless-stopped

networks:
  budget-network:
    driver: bridge

volumes:
  postgres-data:
  caddy-data:
  caddy-config:
