"""Move all last synced data to SFAccount

Revision ID: 026fea9e6cab
Revises: 6695f4cb7b70
Create Date: 2025-09-22 14:06:07.095608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '026fea9e6cab'
down_revision = '6695f4cb7b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simplefin_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_synced_account', sa.DateTime(), nullable=True))

    with op.batch_alter_table('simplefin_credentials', schema=None) as batch_op:
        batch_op.drop_column('last_synced_accounts')
        batch_op.drop_column('last_synced_transactions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simplefin_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_synced_transactions', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_synced_accounts', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('simplefin_account', schema=None) as batch_op:
        batch_op.drop_column('last_synced_account')

    # ### end Alembic commands ###
