"""Separate last synced columnds for accounts and transactions

Revision ID: 0a6b8936a850
Revises: 8a2142bcc3fa
Create Date: 2025-09-16 16:47:11.762315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a6b8936a850'
down_revision = '8a2142bcc3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simplefin_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_synced_accounts', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_synced_transactions', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_synced')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simplefin_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_synced', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('last_synced_transactions')
        batch_op.drop_column('last_synced_accounts')

    # ### end Alembic commands ###
