"""PlaidPlaidAccessToken cursor length to 120

Revision ID: 1e46ab3e1f24
Revises: cd9e88ea4d19
Create Date: 2023-11-12 01:36:43.661215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e46ab3e1f24'
down_revision = 'cd9e88ea4d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_access_token', schema=None) as batch_op:
        batch_op.alter_column('cursor',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaid_access_token', schema=None) as batch_op:
        batch_op.alter_column('cursor',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)

    # ### end Alembic commands ###
