"""Update Theme model

Revision ID: 1f66f5e8d152
Revises: c86022b92476
Create Date: 2025-06-16 11:48:16.445474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f66f5e8d152'
down_revision = 'c86022b92476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('primary_color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('color_contrast', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('color_palette', sa.String(), nullable=True))
        batch_op.drop_column('color')
        batch_op.drop_column('backgroundColor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backgroundColor', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('color_palette')
        batch_op.drop_column('color_contrast')
        batch_op.drop_column('primary_color')
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
