"""empty message

Revision ID: 51089c9a8217
Revises: b8263212bc6a
Create Date: 2025-12-29 10:55:50.141303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51089c9a8217'
down_revision = 'b8263212bc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sqid', sa.String(), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sqid', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('sqid')

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('sqid')

    # ### end Alembic commands ###
