"""Theme color to nullable

Revision ID: 5a7a53b13ab3
Revises: a99206307467
Create Date: 2024-01-04 20:03:33.260566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7a53b13ab3'
down_revision = 'a99206307467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
