"""Add SimpleFINTransaction

Revision ID: 6695f4cb7b70
Revises: 0a6b8936a850
Create Date: 2025-09-18 16:14:57.996946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6695f4cb7b70'
down_revision = '0a6b8936a850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simplefin_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_type', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_synced_transactions', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simplefin_account', schema=None) as batch_op:
        batch_op.drop_column('last_synced_transactions')
        batch_op.drop_column('access_type')

    # ### end Alembic commands ###
