"""Add simpleFIN tables

Revision ID: 8a2142bcc3fa
Revises: ddec5cb29a77
Create Date: 2025-09-14 18:06:29.155063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2142bcc3fa'
down_revision = 'ddec5cb29a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paycheck_prefill')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paycheck_prefill',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('budget_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], name=op.f('paycheck_prefill_budget_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('paycheck_prefill_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('paycheck_prefill_pkey'))
    )
    # ### end Alembic commands ###
