"""Add Theme

Revision ID: a99206307467
Revises: ebd0966e90de
Create Date: 2023-12-29 16:54:04.013687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99206307467'
down_revision = 'ebd0966e90de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plaid_access_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_access_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(length=90), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.VARCHAR(length=90), autoincrement=False, nullable=False),
    sa.Column('cursor', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='plaid_access_token_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='plaid_access_token_pkey')
    )
    # ### end Alembic commands ###
