"""Add sqid column

Revision ID: b8263212bc6a
Revises: 026fea9e6cab
Create Date: 2025-12-29 10:48:46.207384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8263212bc6a'
down_revision = '026fea9e6cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sqid', sa.String(), nullable=False))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sqid', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('sqid')

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('sqid')

    # ### end Alembic commands ###
