"""Add is_transfer to Transaction class

Revision ID: c3e1762fb6d5
Revises: 9c58c6976801
Create Date: 2022-01-10 17:08:55.059723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e1762fb6d5'
down_revision = '9c58c6976801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('is_transfer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'is_transfer')
    # ### end Alembic commands ###
