"""Remove TransactionCategory.new_transaction_id

Revision ID: c86022b92476
Revises: 785d955d4fed
Create Date: 2025-06-11 21:22:25.823393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86022b92476'
down_revision = '785d955d4fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('transaction_category_new_transaction_id_fkey'), type_='foreignkey')
        batch_op.drop_column('new_transaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('transaction_category_new_transaction_id_fkey'), 'transaction', ['new_transaction_id'], ['id'])

    # ### end Alembic commands ###
