"""Add PlaidAccessToken

Revision ID: cd9e88ea4d19
Revises: ebd0966e90de
Create Date: 2023-11-12 00:51:00.000846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9e88ea4d19'
down_revision = 'ebd0966e90de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plaid_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(length=90), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.VARCHAR(length=90), autoincrement=False, nullable=False),
    sa.Column('cursor', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='plaid_token_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='plaid_token_pkey')
    )
    # ### end Alembic commands ###
