"""TransactionCategory.new_transaction_id migration

Revision ID: e0e758560446
Revises: a7927bfb77a6
Create Date: 2025-06-11 20:20:19.926837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e758560446'
down_revision = 'a7927bfb77a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'transaction', ['new_transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('new_transaction_id')

    # ### end Alembic commands ###
