"""Make Budget.is_shared not nullable

Revision ID: fbaec63a3024
Revises: 978025ae8e69
Create Date: 2024-01-29 17:30:09.512467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbaec63a3024'
down_revision = '978025ae8e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('is_shared',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('is_shared',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
